[versions]
activityCompose = "1.8.2"
agp = "8.3.0"
#noinspection GradleDependency
android-compileSdk = "34"
android-minSdk = "24"
android-targetSdk = "34"
annotations = "23.0.0"
kcef = "2024.01.07.1"
kermit = "2.0.2"
kotlin = "2.0.0-Beta4"
jvmTarget = "17"
#noinspection GradleDependency
compose-plugin = "1.6.10-dev1457"
kotlinxSerializationJson = "1.6.3"
webkit = "1.10.0"
jetpack-compose-bom = "2024.02.01"
coroutines-bom = "1.8.0"
kotlinx-atomicfu = "0.23.2"
appcompat = "1.6.1"

[libraries]
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "jetpack-compose-bom" }
coroutines-bom = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-bom", version.ref = "coroutines-bom" }
kotlin-bom = { group = "org.jetbrains.kotlin", name = "kotlin-bom", version.ref = "kotlin" }


annotations = { module = "org.jetbrains:annotations", version.ref = "annotations" }
kotlinx-atomicfu = { module = "org.jetbrains.kotlinx:atomicfu", version.ref = "kotlinx-atomicfu" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }

kcef = { module = "dev.datlag:kcef", version.ref = "kcef" }
kermit = { module = "co.touchlab:kermit", version.ref = "kermit" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android"}
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core" }
kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing" }

kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
webkit = { module = "androidx.webkit:webkit", version.ref = "webkit" }



[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-atomicfu = { id = "org.jetbrains.kotlin.plugin.atomicfu", version.ref = "kotlin" }
kotlin-plugin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-plugin-atomicfu = { id = "org.jetbrains.kotlin.plugin.atomicfu", version.ref = "kotlin" }

android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
dokka = { id = "org.jetbrains.dokka", version = "1.9.20" }
maven-publish = { id = "com.vanniktech.maven.publish", version = "0.25.3" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version = "11.6.1" }

# 下面这个是假的，只是为了占位
jvmTargetPlaceHolder = { id = "org.jdk.kotlin.holder", version.ref = "jvmTarget" }
